sudo: required
services: 
  - docker

before_install:
  - docker build -t tai13492/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run tai13492/docker-react-tutorial npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-tutorial"
  env: "DockerReactTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-2-248357856379"
  bucket_path: "docker-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

    